language: cpp
compiler:
  - clang++
before_install:
    - sudo apt-get install build-essential m4 lzip unzip
    - ./scripts/install-dependencies.sh
script: make nosetests
notifications:
    email: false
